import { api } from "@/convex/_generated/api";
import convex from "@/lib/convexClient";
import { createAgent, createTool, openai } from "@inngest/agent-kit";
import { Id } from "@/convex/_generated/dataModel";
import z from "zod";
import { sendBrevo } from "@/lib/bervo/sendMail";

const connectDB = createTool({
  name: "connectdb",
  description: "Connect to DB to save resume analysis results.",
  parameters: z.object({
    resumeId: z
      .string()
      .describe("Resume id for referring the resume data in db"),
    sampleJobPost: z
      .string()
      .describe("The sample post matched with the user resume"),
    role: z.string().describe("The role user applying for from sample post"),
    resumeScore: z.number().describe("Overall ATS score like '85%'"),

    matchedSkills: z
      .array(z.string())
      .describe("Skills that match the job post"),
    missingSkills: z.array(z.string()).describe("Skills that are missing"),
    recommendations: z
      .array(z.string())
      .describe("Suggestions to improve alignment"),
    keywordSuggestions: z
      .array(z.string())
      .describe("Keywords to add to improve ATS match"),
    experienceGap: z.string().describe("Summary of the experience gap if any"),
    aisummary: z.string().describe("Overall summary of resume"),

    skillsMatch: z
      .number()
      .describe("Percentage of job-required skills matched"),
    experienceMatch: z
      .boolean()
      .describe("Whether the experience matches the job requirements"),
    keywordDensity: z
      .number()
      .describe("Percentage of job keywords present in the resume"),
    strengths: z.array(z.string()).describe("Strong areas in the resume"),
    warnings: z.array(z.string()).describe("Gaps or risks in the resume"),
    userMail: z.string().describe("Email address of the user"),
  }),

  handler: async (params, context) => {
    const {
      resumeId,
      resumeScore,
      matchedSkills,
      missingSkills,
      recommendations,
      keywordSuggestions,
      experienceGap,
      sampleJobPost,
      role,
      aisummary,
      skillsMatch,
      experienceMatch,
      keywordDensity,
      strengths,
      warnings,
      userMail,
    } = params;

    const result = await context.step?.run("save_resume_analysis", async () => {
      try {
        await convex.mutation(api.resume.updateResume, {
          id: resumeId as Id<"resume">,
          sampleJobPost,
          role,
          resumeScore,
          matchedSkills,
          missingSkills,
          recommendations,
          keywordSuggestions,
          experienceGap,
          aisummary,
          skillsMatch,
          experienceMatch,
          keywordDensity,
          strengths,
          warnings,
          status: "completed",
        });

        if (userMail !== "Not_provided") {
          await sendBrevo({
            to: userMail,
            subject: `Your Resume Analysis for ${role}`,
            html: `
            <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Resume Analysis Results</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f9fafb;
      margin: 0;
      padding: 0;
    }
    button:{
      background-color: #4f46e5;
      color: #ffffff;
      border: none;
      border-radius: 4px;
      padding: 12px 16px;
      cursor: pointer;
      font-size: 16px;
    }
    button:hover {
      background-color: #4338ca;
    }
    .container {
      max-width: 600px;
      margin: 0 auto;
      background-color: #ffffff;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      display:flex;
      flex-direction: column;
      gap: 12px;
    }
    .header {
      background-color: #4f46e5;
      color: #ffffff;
      padding: 16px;
      text-align: center;
      font-size: 20px;
      font-weight: bold;
    }
    .content {
      padding: 20px;
      line-height: 1.6;
    }
    .label {
      font-weight: bold;
      margin-top: 12px;
      display: block;
      color: #111827;
    }
    .value {
      margin-bottom: 16px;
      color: #374151;
    }
    .footer {
      background-color: #f3f4f6;
      color: #6b7280;
      text-align: center;
      padding: 12px;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">Your Resume Analysis Result</div>
    <div class="content">
      <span class="label">Role:</span>
      <div class="value">${role}</div>

      <span class="label">AI Summary:</span>
      <div class="value">${aisummary}</div>
    </div>
    <button><a href = "https://resumae-ai.vercel.app/resume/${resumeId}">Full Report</a></button>
    <div class="footer">
      Generated by Resume Analysis AI • ${new Date().toLocaleDateString()}
    </div>
  </div>
</body>
</html>`,
          });
        }
        return { success: true };
      } catch (error) {
        return {
          success: false,
          error: error instanceof Error ? error.message : "Unknown error",
        };
      }
    });

    if (result?.success) {
      context.network?.state.kv.set("saved_to_db", true);
    }

    return result;
  },
});

export const saveToDb = createAgent({
  name: "savetodb",
  description: "Save analysis results to database",
  model: openai({
    model: "gpt-4o",
    baseUrl: process.env.OPENAI_BASEURL,
    apiKey: process.env.OPENAI_API_KEY,
  }),
  system: `
You are a resume analysis saving agent. Your only task is to call the "connectdb" tool with the provided resume evaluation results.

Ensure all of the following fields are included exactly as described and also check there is no gibberish: 

- resumeId: string
- userMail: string
- sampleJobPost: string
- role: string
- resumeScore: number (0–100)
- matchedSkills: array of strings
- missingSkills: array of strings
- recommendations: array of strings
- keywordSuggestions: array of strings
- experienceGap: string
- aisummary: string
- skillsMatch: number (0–100)
- experienceMatch: boolean
- keywordDensity: number (0–100)
- strengths: array of strings
- warnings: array of strings

DO NOT generate or explain anything outside the tool call.
Only respond with the correct tool and parameters.
if sendmail is provided with valid mail then send the data through mail.

`,

  tools: [connectDB],
});
